### ISSUE TITLE
Add support for automated testing

### ISSUE THREAD

**Issue by christiam** [NCBI-Codeathons/Taxonomy-specific-RPS-BLAST-part-I#12]

**Comment by christiam** [comment]
@mingzhangyang How about this for automated checking?
https://travis-ci.org/christiam/Taxonomy-specific-RPS-BLAST-part-I

**Comment by mingzhangyang** [comment]
It's really cool. 👍

**Comment by christiam** [comment]
Thanks! I added a pull request for this change: #22
