### ISSUE TITLE
-loglevel DEBUG not working

### ISSUE THREAD

**Issue by mingzhangyang** [NCBI-Codeathons/Taxonomy-specific-RPS-BLAST-part-I#15]
Running the command with "-loglevel DEBUG" is supposed to print all the nodes (with child nodes) removed from the tree, as defined in sayGoodbye method in tree.py 
But it didn't print to the console. Please check. @christiam 
Thanks.

**Comment by christiam** [comment]
@mingzhangyang , to print debugging output to the console, you should also add `-logfile stderr` to the command line, otherwise the debugging output goes to `dtrt.log` by default.
