### ISSUE TITLE
taxadb not working

### ISSUE THREAD

**Issue by mingzhangyang** [NCBI-Codeathons/Taxonomy-specific-RPS-BLAST-part-I#16]
@christiam I tested the taxadb version, but it seems not working. I created a testing branch with a little bit of changes. Could you please check to see what the issue is. Thanks.

**Comment by christiam** [comment]
@mingzhangyang, what specifically isn't working? could you please provide an example command line and error message?

**Comment by mingzhangyang** [comment]
I rerun the `make check` command and got the error below
```
source .env/bin/activate && \
for f in test.py dtrt.py check_biopython.py check_taxadb.py; do python -m py_compile $f ; done 
#python3 -m unittest test dtrt check_biopython check_taxadb
#python3 -m unittest discover -s tests
#time -p python3 -m doctest map.py
#time -p py.test *.py
#time -p py.test tests
source .env/bin/activate && ./check_taxadb.py 9606 2 10090 2157
Table taxa does not exist
make: *** [check] Error 1
```

**Comment by christiam** [comment]
It could be that the local taxadb data hasn't been initialized or that its configuration is not set properly (i.e.: misconfigured `TAXADB_CONFIG` environment variable).

I committed a workaround for the `make check` target, but please also be sure that `taxadb.sqlite` exists in the current working directory and that the `TAXADB_CONFIG` environment variable is set correctly (e.g.: refers to `etc/taxadb.cfg`).
